[libc++][Android] Enable libc++ testing on Android
Automated commit created by applying diff 549856

Phabricator-ID: PHID-HMBT-7np2cuasgskz2qmbtila
Review-ID: D139147

diff --git a/libcxx/utils/ci/run-buildbot b/libcxx/utils/ci/run-buildbot
--- a/libcxx/utils/ci/run-buildbot
+++ b/libcxx/utils/ci/run-buildbot
@@ -51,6 +51,8 @@ GIT_CLANG_FORMAT    The git-clang-format binary to use in the 'format' builder.
 
 ENABLE_CLANG_TIDY   Whether to compile and run clang-tidy checks. This variable
                     is optional.
+
+ANDROID_EMU_IMG     The name of an Android emulator OS image.
 EOF
 }
 
@@ -147,6 +149,13 @@ function generate-cmake-libcxx-win() {
           -DLLVM_ENABLE_RUNTIMES="libcxx" \
           -DCMAKE_C_COMPILER=clang-cl \
           -DCMAKE_CXX_COMPILER=clang-cl \
+          "${@}"
+}
+
+function generate-cmake-android() {
+    generate-cmake-base \
+          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
+          -DLIBCXX_CXX_ABI=libcxxabi \
           "${@}"
 }
 
@@ -684,6 +693,52 @@ aix)
                    -DLIBUNWIND_TEST_CONFIG="ibm-libunwind-shared.cfg.in"
     check-abi-list
     check-runtimes
+;;
+android-ndk)
+    clean
+
+    . "${MONOREPO_ROOT}/libcxx/utils/ci/vendor/android/emulator-functions.sh"
+    if ! validate_emu_img "${ANDROID_EMU_IMG}"; then
+        echo "error: ANDROID_EMU_IMG must be a valid emulator image." >&2
+        exit 1
+    fi
+    ARCH=$(arch_of_emu_img ${ANDROID_EMU_IMG})
+
+    # Compile the builtins archive and libunwind.a and add them to a patched
+    # resource directory, and generate Clang wrapper scripts.
+    "${MONOREPO_ROOT}/libcxx/utils/ci/vendor/android/build-toolchain.sh" \
+        --llvm-root "${MONOREPO_ROOT}" \
+        --output-dir "${BUILD_DIR}/android-toolchain" \
+        --cmake "${CMAKE}" --ninja "${NINJA}" --arch ${ARCH}
+    export CC="${BUILD_DIR}/android-toolchain/bin/clang"
+    export CXX="${BUILD_DIR}/android-toolchain/bin/clang++"
+
+    # The NDK libc++_shared.so is always built against the oldest supported API
+    # level. When tests are run against a device with a newer API level, test
+    # programs can be built for any supported API level, but building for the
+    # newest API (i.e. the system image's API) is probably the most interesting.
+    PARAMS="target_triple=$(triple_of_arch ${ARCH})$(api_of_emu_img ${ANDROID_EMU_IMG})"
+    generate-cmake-android -C "${MONOREPO_ROOT}/runtimes/cmake/android/Arch-${ARCH}.cmake" \
+                           -C "${MONOREPO_ROOT}/libcxx/cmake/caches/AndroidNDK.cmake" \
+                           -DCMAKE_SYSROOT=/opt/android/ndk/sysroot \
+                           -DLIBCXX_TEST_PARAMS="${PARAMS}" \
+                           -DLIBCXXABI_TEST_PARAMS="${PARAMS}"
+    check-abi-list
+    ${NINJA} -vC "${BUILD_DIR}" install-cxx install-cxxabi
+
+    # Start the emulator and make sure we can connect to the adb server running
+    # inside of it.
+    "${MONOREPO_ROOT}/libcxx/utils/ci/vendor/android/start-emulator.sh" ${ANDROID_EMU_IMG}
+    . "${MONOREPO_ROOT}/libcxx/utils/ci/vendor/android/setup-env-for-emulator.sh"
+
+    # Create adb_run early to avoid concurrent `mkdir -p` of common parent
+    # directories.
+    adb shell mkdir -p /data/local/tmp/adb_run
+    adb push "${BUILD_DIR}/lib/libc++_shared.so" /data/local/tmp/libc++/libc++_shared.so
+    echo "+++ Running the libc++ tests"
+    ${NINJA} -vC "${BUILD_DIR}" check-cxx
+    echo "+++ Running the libc++abi tests"
+    ${NINJA} -vC "${BUILD_DIR}" check-cxxabi
 ;;
 #################################################################
 # Insert vendor-specific internal configurations below.
